name: Production
on:
  push:
    branches:
      - main

jobs:
  testAndDeploy:
    uses: ./.github/workflows/test-and-deploy.yml
    with:
      env: production
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET  }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
